---
# F5 playbook to create nodes and add them to pool
- name: Create nodes
  bigip_node:
         provider: "{{ provider }}"
         description: "Node {{ item.name }}"
         name: "{{ item.name }}"
         host: "{{ item.host }}"
         partition: "{{ partition }}"
         state: "{{ state }}"
  loop: "{{ nodes }}"
  when: nodes is defined
  
  #when: state == "absent"
